### ISSUE TITLE
access the initial light brightness

### ISSUE THREAD

**Issue by fry2k** [hurenkam/node-red-contrib-mh-hue#3]
Hi,

I came from hue magic. Your extension looks very promising but I'm missing one functionality.
I turn off my lights completely. I have sliders at my node red dashboard and want to set the slider to the current brightness level when the light is turned on.
I configured the lights that they use the last brightness setting when they power on.

At the node red editor the brightness for the light is shown as text below the node. This works also for powered off lights. Seems like this information is stored at the bridge.
Is there a way to access this information somehow?

When I change the brightness with a light node the output of this node receives the brightness value.

Thanks for helping. Hope I didn't missed this part at the readme. Hue magic has a checkbox to skip the initial message from this node.

**Comment by hurenkam** [comment]
If i understand you correctly, you would like for the light (as well as room & zone) nodes to expose their initial state when you start the flow?

This information is indeed available at the bridge on request, and upon startup the plugin indeed already gathers this information and provides it to the service nodes, so internally they already have the information present.

At this time however, that information is not exposed, because it does not contain state changes (but current state).

It is technically not too hard to expose this information, but i need to keep this separate from the normal state changes. Probably that can be done using a different message type or format. I will consider taking this up for the next minor update.

**Comment by hurenkam** [comment]
Looking at the code, it looks like the ResourceNode.start() method is called when the requested data is available (that is where it also updates the editor status). 
It just needs to send the appropriate message out.

**Comment by hurenkam** [comment]
This feature should be available now in version 0.6.3

**Comment by fry2k** [comment]
awesome thank you so much for your fast feature! very much appreciated. 

works perfect and exactly what I was looking for.

There is a bug with clicking the checkbox at macOS and safari. I'm going to create a pull request for that.
